[package]
name = "sudoku"
version = "0.1.0"
edition = "2021"
default-run = "sudoku"

[dependencies]
criterion = "0.5.1"
crossterm = "0.27.0"
rand = "0.8.5"

[[bench]]
name = "benchmark"
harness = false

[[bin]]
name = "example"
test = false
bench = false